# Generated by Django 6.1.1 on 2026-09-27 19:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_daily_hours',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('16'))]),
        ),
    ]
