# Generated by Django 6.1.1 on 2026-10-08 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_daily_hours',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
