# Generated by Django 6.1.1 on 2026-09-25 00:24

import django.db.models.deletion
from django.db import migrations, models


def check_no_uncategorized_subtasks(apps, schema_editor):
    # A null category crashes the frontend's subtask card, so there is no safe
    # default to backfill with: fail loudly and let a person decide.
    Subtasks = apps.get_model('event', 'Subtasks')
    missing = Subtasks.objects.filter(category__isnull=True).count()
    if missing:
        raise RuntimeError(
            f"{missing} subtask(s) have no category. Assign one before migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_seed_predefinidos'),
    ]

    operations = [
        migrations.RunPython(check_no_uncategorized_subtasks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subtasks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='event.category'),
        ),
    ]
