# Generated by Django 6.1.1 on 2026-09-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_move_user_to_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_kind',
            field=models.CharField(blank=True, choices=[('color', 'color'), ('image', 'image')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
