"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import dj_database_url
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads environment variables from .env (if present) and from the system environment.
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Runtime environment: dev | qa | prod. Controls the defaults below.
ENVIRONMENT = env("ENVIRONMENT", default="dev")

# SECURITY WARNING: keep the secret key used in production secret!
# In dev an insecure default is allowed so the app can start without a .env.
# In qa/prod SECRET_KEY is mandatory; if missing the app must fail to boot.
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-8_(7@2lv%as@*uldp$0n1z=u%wzp=2@!039ka43a^op-nc_p4a"
    if ENVIRONMENT == "dev"
    else environ.Env.NOTSET,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=(ENVIRONMENT == "dev"))

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Render injects the service's external hostname in this variable.
RENDER_EXTERNAL_HOSTNAME = env("RENDER_EXTERNAL_HOSTNAME", default=None)
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'event',
    'accounts',
    'planning',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# If DATABASE_URL is present we use Postgres (Render provides it).
# Otherwise we fall back to SQLite so the project can start without a .env.
if env("DATABASE_URL", default=None):
    # Supabase's pooler exposes two ports with different behavior:
    #   5432 -> session pooler: supports persistent connections (what we want).
    #   6543 -> transaction pooler: recycles the connection between transactions,
    #           so it doesn't support conn_max_age or prepared statements.
    # We detect the port so nothing breaks if someone pastes the 6543 URL.
    _db = dj_database_url.config(conn_max_age=600, ssl_require=True)

    if str(_db.get("PORT")) == "6543":
        _db["CONN_MAX_AGE"] = 0
        _db.setdefault("OPTIONS", {})["prepare_threshold"] = None

    DATABASES = {"default": _db}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# In dev emails are printed to the console. In qa/prod they're sent via SMTP
# with credentials taken from the environment; if EMAIL_HOST isn't set, the
# dummy backend is used so the app doesn't fail to boot (emails are discarded).
if ENVIRONMENT == "dev":
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }
elif env("EMAIL_HOST", default=""):
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": env("EMAIL_HOST"),
                "port": env.int("EMAIL_PORT", default=587),
                "username": env("EMAIL_HOST_USER", default=""),
                "password": env("EMAIL_HOST_PASSWORD", default=""),
                "use_tls": env.bool("EMAIL_USE_TLS", default=True),
            },
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.dummy.EmailBackend",
        },
    }

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@planificapp.local")


# CORS / CSRF
# The backend is consumed by the frontend on another domain, so the allowed
# origins are configured explicitly per environment.
# NEVER use CORS_ALLOW_ALL_ORIGINS: each environment must declare its origins.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = True


# Django REST Framework
# The browsable API renderer is only enabled in DEBUG, so it's not exposed
# in qa/prod.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
    + (["rest_framework.renderers.BrowsableAPIRenderer"] if DEBUG else []),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'event.exceptions.custom_exception_handler',
}


# Extra security once DEBUG is off (qa and prod).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    # Render's health check can arrive without the X-Forwarded-Proto header.
    # If that happens, the redirect to https returns a 301 and Render marks
    # the deploy as failed even though the service is healthy. We exempt
    # that route from the redirect.
    SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # The frontend lives on another domain (planificapp-web-*.onrender.com) and
    # calls the API with credentials: "include". With the default "Lax" value
    # the browser does NOT attach the session cookie on cross-site fetch
    # requests, so authentication wouldn't work. "None" requires Secure
    # cookies, which are already enabled above.
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"

    # HSTS only in prod: in qa we'd rather be able to revert to HTTP without
    # waiting for the header to expire in users' browsers.
    if ENVIRONMENT == "prod":
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True


SPECTACULAR_SETTINGS = {
    'TITLE': 'Miniproyecto Event Management API',
    'DESCRIPTION': '''
Welcome to the Event Management API. 
    
### Key Features
- **Events:** Manage top-level project events, with deadlines, priority and estimated progress.
- **Subtasks:** Track individual action items under each event.
- **Enums:** Custom database enums enforce strict validation for statuses and categories.
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Optional styling settings:
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
    },
}